export * from './primeng/primeng-tabview-basic-example.component';
export * from './primeng/primeng-tabview-size-example.component';
export * from './primeng/primeng-tabview-router-example.component'
export * from './primeng/primeng-tabview-model-example.component'
export * from './primeng/primeng-first-tab.component';
export * from './primeng/primeng-second-tab.component';
export * from './govcz/govcz-tabview-router-example.component';
export * from './govcz/govcz-tabview-basic-example.component';
export * from './govcz/govcz-tabview-size-example.component';
export * from './govcz/govcz-tabview-model-example.component';
export * from './govcz/govcz-first-tab.component';
export * from './govcz/govcz-second-tab.component';