import { CommonIcons } from '@verisoft/ui-core';

export const Icons: CommonIcons = {
  add: 'plus-lg',
  minus: 'dash',
  delete: 'trash',
  filter: 'filter',
  download: 'upload',
  save: 'download',
  print: 'print-fill',
  edit: 'pencil',
  calendar: 'calendar',
  settings: 'gear',
  house: 'house-door-fill',
  chevronRight: 'chevron-right',
  chevronDown: 'chevron-down',
  chevronLeft: 'chevron-left',
  chevronUp: 'chevron-up',
  checkbox: 'check-square',
  warning: 'exclamation-triangle-fill',
  search: 'search',
  action: 'bars',
  user: 'user',
  crossCircle: 'x-circle',
  infoCircle: 'info-circle',
  cross: 'x-lg',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  questionCircle: 'question-circle',
  checkCircle: 'check-circle',
  sitemap: 'diagram',
  check: 'check-lg',
  envelope: 'envelope',
};
