import { CommonIcons } from '@verisoft/ui-core';

export const Icons: CommonIcons = {
  add: 'pi pi-plus',
  minus: 'pi pi-minus',
  delete: 'pi pi-trash',
  filter: 'pi pi-filter',
  download: 'pi pi-download',
  save: 'pi pi-save',
  print: 'pi pi-print',
  calendar: 'pi pi-calendar',
  edit: 'pi pi-pencil',
  settings: 'pi pi-cog',
  house: 'pi pi-home',
  chevronRight: 'pi pi-chevron-right',
  chevronLeft: 'pi pi-chevron-left',
  chevronDown: 'pi pi-chevron-down',
  chevronUp: 'pi pi-chevron-up',
  checkbox: 'pi pi-check',
  warning: 'pi pi-exclamation-triangle',
  search: 'pi pi-search',
  action: 'pi pi-bars',
  user: 'pi pi-user',
  crossCircle: 'pi pi-times-circle',
  infoCircle: 'pi pi-info-circle',
  cross: 'pi pi-times',
  arrowLeft: 'pi pi-arrow-left',
  arrowRight: 'pi pi-arrow-right',
  questionCircle: 'pi pi-question-circle',
  checkCircle: 'pi pi-check-circle',
  sitemap: 'pi pi-sitemap',
  check: 'pi pi-check',
  envelope: 'pi pi-envelope',
};
